import { TCondominium } from "../../@types/data/condominium"

export const FDcondos: TCondominium[] = [
  {
    id: "1",
    name: "Condomínio 1",
    units: 8,
    cnpj: "11222333000199",
    image: null,
    address: {
      street: "Rua legal",
      number: "123",
      cep: "88777666",
      neighborhood: "Centro",
      city: "Florianópolis",
      state: "SC",
    },
    manager: {
      id: "9",
      email: "sindico@legal.com",
      image: null,
      name: "Síndico",
      profile: "manager",
      since: "'2024-01-15T03:00:00.000Z'",
      status: "active",
      surname: "Legal",
    },
    electionFile: undefined,
  },
  {
    id: "2",
    name: "Condomínio 2",
    units: 8,
    cnpj: "11222333000199",
    image: null,
    address: {
      street: "",
      number: "",
      cep: "",
      neighborhood: "",
      city: "Florianópolis",
      state: "SC",
    },
    manager: {
      id: "9",
      email: "sindico@legal.com",
      image: null,
      name: "Síndico",
      profile: "manager",
      since: "'2024-01-15T03:00:00.000Z'",
      status: "active",
      surname: "Legal",
    },
    electionFile: undefined,
  },
]
