import { TBudget } from "../../@types/data/budget"

export const FDmanagerBudgets: TBudget[] = [
  {
    id: "1",
    condominium: {
      id: "1",
      name: "Condomínio legal",
      units: 8,
      cnpj: "11222333000199",
      image: null,
      address: {
        street: "Rua legal",
        number: "123",
        cep: "88777666",
        neighborhood: "Centro",
        city: "Florianópolis",
        state: "SC",
      },
    },
    urgent: false,
    category: "Jardinagem",
    subcategory: "Corte de grama",
    title: "Corte de grama profissional",
    description: "Cortar gramado frontal do prédio",
    start: "2024-11-01",
    end: "2024-11-15",
    date: "2024-11-10",
    attached: [],
    status: "approved",
  },
  {
    id: "2",
    condominium: {
      id: "1",
      name: "Condomínio legal",
      units: 8,
      cnpj: "11222333000199",
      image: null,
      address: {
        street: "Rua legal",
        number: "123",
        cep: "88777666",
        neighborhood: "Centro",
        city: "Florianópolis",
        state: "SC",
      },
    },
    urgent: false,
    category: "Jardinagem",
    subcategory: "Corte de grama",
    title: "Corte de grama profissional",
    description: "Cortar gramado frontal do prédio",
    start: "2024-11-01",
    end: "2024-11-17",
    date: "2024-11-10",
    attached: [],
    status: "awaiting",
  },
  {
    id: "3",
    condominium: {
      id: "1",
      name: "Condomínio legal",
      units: 8,
      cnpj: "11222333000199",
      image: null,
      address: {
        street: "Rua legal",
        number: "123",
        cep: "88777666",
        neighborhood: "Centro",
        city: "Florianópolis",
        state: "SC",
      },
    },
    urgent: false,
    category: "Jardinagem",
    subcategory: "Corte de grama",
    title: "Corte de grama profissional",
    description: "Cortar gramado frontal do prédio",
    start: "2024-11-01",
    end: "2024-11-18",
    date: "2024-11-10",
    attached: [],
    status: "approved",
  },
  {
    id: "4",
    condominium: {
      id: "1",
      name: "Condomínio legal",
      units: 8,
      cnpj: "11222333000199",
      image: null,
      address: {
        street: "Rua legal",
        number: "123",
        cep: "88777666",
        neighborhood: "Centro",
        city: "Florianópolis",
        state: "SC",
      },
    },
    urgent: false,
    category: "Jardinagem",
    subcategory: "Corte de grama",
    title: "Corte de grama profissional",
    description: "Cortar gramado frontal do prédio",
    start: "2024-11-01",
    end: "2024-11-18",
    date: "2024-11-10",
    attached: [],
    status: "awaiting",
  },
]
