import { TUser } from "../../@types/data/user"

export const FDpeople: any[] = [
  {
    id: "1",
    name: "StatusTech",
    surname: "Top",
    email: "email@email.com",
    active: true,
    document: {
      type: "cpf",
      register: "",
      date: new Date().toISOString(),
    },
    profile: "ADMIN",
    image: null,
  },
  {
    id: "2",
    name: "Júlio",
    surname: "Cesar",
    email: "julio@cesar.com",
    active: true,
    document: {
      type: "cpf",
      register: "",
      date: new Date().toISOString(),
    },
    profile: "SINDICO",
    image: null,
    phone1: "",
    phone2: "",
    experience: "01",
    since: "",
    condos: [],
  },
  {
    id: "3",
    name: "Alexandre",
    surname: "O Grande",
    email: "alexandre@grande.com",
    active: true,
    document: {
      type: "cpf",
      register: "",
      date: new Date().toISOString(),
    },
    profile: "SINDICO",
    image: null,
    phone1: "",
    phone2: "",
    experience: "01",
    since: "",
    condos: [],
  },
  {
    id: "4",
    name: "Alexandre",
    active: true,
    image: null,
    profile: "PRESTADOR",
    franchises: [],
    fantasyName: "",
    address: {
      cep: "",
      country: "",
      state: "",
      city: "",
      street: "",
      number: "",
      complement: "",
    },

    responsable: "",
    website: "",
    email: "alexandre@grande.com",
    phone1: "",
    phone2: "",
    phone3: "",

    // Comercial info
    socialRole: "",
    document: {
      type: "cnpj",
      register: "",
      date: new Date().toISOString(),
    },
    cnpjCard: "",
    category: "",

    // Documentation
    federalCnd: "",
    federalCndStart: "",
    federalCndEnd: "",
    federalCndFree: false,
    federalCndDocument: null,

    stateCnd: "",
    stateCndStart: "",
    stateCndEnd: "",
    stateCndFree: false,
    stateCndDocument: null,

    cityCnd: "",
    cityCndStart: "",
    cityCndEnd: "",
    cityCndFree: false,
    cityCndDocument: null,

    fgtsCnd: "",
    fgtsCndStart: "",
    fgtsCndEnd: "",
    fgtsCndFree: false,
    fgtsCndDocument: null,

    pendencies: {
      federalCnd: "free",
      stateCnd: "free",
      cityCnd: "free",
      fgts: "free",
    },
  },
]
