import { TUser } from "../../@types/data/user"

export const FDpeople: TUser[] = [
  {
    id: "1",
    name: "StatusTech",
    surname: "Top",
    email: "email@email.com",
    active: true,
    document: {
      type: "cpf",
      register: "",
      date: new Date().toISOString(),
    },
    profile: "admin",
    image: null,
  },
  {
    id: "2",
    name: "Júlio",
    surname: "Cesar",
    email: "julio@cesar.com",
    active: true,
    document: {
      type: "cpf",
      register: "",
      date: new Date().toISOString(),
    },
    profile: "manager",
    image: null,
    phone1: "",
    phone2: "",
    experience: "01",
    since: "",
    condos: [],
  },
  {
    id: "3",
    name: "Alexandre",
    surname: "O Grande",
    email: "alexandre@grande.com",
    active: true,
    document: {
      type: "cpf",
      register: "",
      date: new Date().toISOString(),
    },
    profile: "manager",
    image: null,
    phone1: "",
    phone2: "",
    experience: "01",
    since: "",
    condos: [],
  },
]
